apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aiot.fullname" . }}
  labels:
    {{- include "aiot.labels" . | nindent 4 }}
data:
  aiot.yaml: |
    runtime:
      mode: distributed
    telemetry:
      endpoint: "http://otel-collector:4317"
      level: "info"
