apiVersion: v1
kind: ConfigMap
metadata:
  name: aiot-config
  labels:
    app: aiot
data:
  aiot.yaml: |
    runtime:
      mode: distributed
    telemetry:
      endpoint: "http://otel-collector:4317"
      level: "info"
